apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend
    spec:
      containers:
      - image: bruno11n1/frontend:RC-16.7ef2714
        name: frontend
        ports:
        - containerPort: 5000
        env:
        - name: BACKEND_URL
          value: http://backend-service:5001
        resources: {}
status: {}
